#pragma once

// PulpKit -- a circuit-modelled analog drum machine.
//
// One polyphonic Processor that owns one instance of every kit voice and routes
// a MIDI note-on to the voice that lives on that note. Every voice is a struck
// or gated circuit model (never a sample), so the kit is one persistent
// instrument rather than a bank of one-shots: each drum rings in its own state
// and a repeated hit superposes onto the tail already in flight.
//
// The topology is fixed -- one note map, no runtime routing -- so this is a
// Processor, not a graph. Polyphony across the voices is a Processor concern;
// every voice advances every sample and the block sum is the mix.
//
// The note map mirrors the classic analog-drum layout:
//   36 kick   37 rim   38/40 snare   39 clap
//   41/43 low tom   45/47 mid tom   48/50 hi tom
//   42/44 closed hat (chokes the open hat)   46 open hat   49 cymbal
//   51/56 cowbell   70 maracas   75 clave
//
// Control surface: every voice exposes exactly four parameters -- Level, Tune,
// Decay, Tone -- in that order, grouped voice-by-voice so a host shows the same
// four knobs per sound every time. Each maps onto that voice's uniform
// set_level / set_tune / set_decay / set_tone. The stock knob positions (Level
// 100%, Tune 1.0, Decay 50%, Tone 50%) reproduce the calibrated reference sound
// exactly; the controls only open musical range around it. The snare keeps its
// tone/snap Balance as a fifth, voice-specific control.
//
// Voices calibrated to the measured output of the reference instrument; the
// sound is generated by the circuit models sample by sample. No reference audio
// is embedded.

#include "va_drum_voice.hpp"

#include "voices/clap_voice.hpp"
#include "voices/cowbell_voice.hpp"
#include "voices/maracas_voice.hpp"
#include "voices/membrane_voice.hpp"
#include "voices/metallic_voice.hpp"
#include "voices/rim_clave_voice.hpp"
#include "voices/snare_voice.hpp"

#include <pulp/audio/buffer.hpp>
#include <pulp/format/processor.hpp>
#include <pulp/midi/buffer.hpp>
#include <pulp/state/store.hpp>

#include <algorithm>
#include <cstdint>
#include <memory>

namespace pulp::examples {

// Parameter ids, grouped voice-by-voice. Every voice contributes four ids in a
// fixed Level / Tune / Decay / Tone order; the snare adds a trailing Balance.
// The ids are contiguous per voice so the group offsets below are the only
// arithmetic the Processor needs.
enum PulpKitParams {
    kPulpKitKickLevel = 0,
    kPulpKitKickTune,
    kPulpKitKickDecay,
    kPulpKitKickTone,

    kPulpKitSnareLevel,
    kPulpKitSnareTune,
    kPulpKitSnareDecay,
    kPulpKitSnareTone,
    kPulpKitSnareBalance,  // voice-specific extra: tone-vs-snap mix

    kPulpKitLowTomLevel,
    kPulpKitLowTomTune,
    kPulpKitLowTomDecay,
    kPulpKitLowTomTone,

    kPulpKitMidTomLevel,
    kPulpKitMidTomTune,
    kPulpKitMidTomDecay,
    kPulpKitMidTomTone,

    kPulpKitHiTomLevel,
    kPulpKitHiTomTune,
    kPulpKitHiTomDecay,
    kPulpKitHiTomTone,

    kPulpKitRimLevel,
    kPulpKitRimTune,
    kPulpKitRimDecay,
    kPulpKitRimTone,

    kPulpKitClaveLevel,
    kPulpKitClaveTune,
    kPulpKitClaveDecay,
    kPulpKitClaveTone,

    kPulpKitClapLevel,
    kPulpKitClapTune,
    kPulpKitClapDecay,
    kPulpKitClapTone,

    kPulpKitClosedHatLevel,
    kPulpKitClosedHatTune,
    kPulpKitClosedHatDecay,
    kPulpKitClosedHatTone,

    kPulpKitOpenHatLevel,
    kPulpKitOpenHatTune,
    kPulpKitOpenHatDecay,
    kPulpKitOpenHatTone,

    kPulpKitCymbalLevel,
    kPulpKitCymbalTune,
    kPulpKitCymbalDecay,
    kPulpKitCymbalTone,

    kPulpKitCowbellLevel,
    kPulpKitCowbellTune,
    kPulpKitCowbellDecay,
    kPulpKitCowbellTone,

    kPulpKitMaracasLevel,
    kPulpKitMaracasTune,
    kPulpKitMaracasDecay,
    kPulpKitMaracasTone,

    kPulpKitParamCount,
};

class PulpKit : public format::Processor {
public:
    format::PluginDescriptor descriptor() const override {
        return {
            .name = "PulpKit",
            .manufacturer = "Pulp",
            .bundle_id = "com.pulp.pulp-kit",
            .version = "1.0.0",
            .category = format::PluginCategory::Instrument,
            .input_buses = {},
            .output_buses = {{"Main Out", 2, false}},
            .accepts_midi = true,
        };
    }

    void define_parameters(state::StateStore& store) override {
        // Four knobs per voice, always in the same order. Level is a percentage
        // around the calibrated loudness (100% == today's level, and the range
        // reaches to +6 dB); Tune is a pitch multiplier centred on 1.0; Decay
        // and Tone are 0..100% knobs centred on 50%, which is each voice's
        // calibrated point. The defaults reproduce the reference sound exactly.
        int group = 0;
        auto add_voice = [&store, &group](state::ParamID base, const char* voice) {
            const int g = ++group;
            const std::string name = voice;
            store.add_parameter({.id = base + 0,
                                 .name = name + " Level",
                                 .unit = "%",
                                 .range = {0.0f, 200.0f, 100.0f, 0.1f},
                                 .group_id = g});
            store.add_parameter({.id = base + 1,
                                 .name = name + " Tune",
                                 .unit = "x",
                                 .range = {0.5f, 2.0f, 1.0f, 0.01f},
                                 .group_id = g});
            store.add_parameter({.id = base + 2,
                                 .name = name + " Decay",
                                 .unit = "%",
                                 .range = {0.0f, 100.0f, 50.0f, 0.1f},
                                 .group_id = g});
            store.add_parameter({.id = base + 3,
                                 .name = name + " Tone",
                                 .unit = "%",
                                 .range = {0.0f, 100.0f, 50.0f, 0.1f},
                                 .group_id = g});
            return g;
        };

        add_voice(kPulpKitKickLevel, "Kick");
        const int sg = add_voice(kPulpKitSnareLevel, "Snare");
        // The snare's fifth control lives in the snare group, after its four
        // uniform knobs: the tone-vs-snap balance, a snare-only character.
        store.add_parameter({.id = kPulpKitSnareBalance,
                             .name = "Snare Balance",
                             .unit = "%",
                             .range = {0.0f, 100.0f, 50.0f, 0.1f},
                             .group_id = sg});
        add_voice(kPulpKitLowTomLevel, "Low Tom");
        add_voice(kPulpKitMidTomLevel, "Mid Tom");
        add_voice(kPulpKitHiTomLevel, "Hi Tom");
        add_voice(kPulpKitRimLevel, "Rim");
        add_voice(kPulpKitClaveLevel, "Clave");
        add_voice(kPulpKitClapLevel, "Clap");
        add_voice(kPulpKitClosedHatLevel, "Closed Hat");
        add_voice(kPulpKitOpenHatLevel, "Open Hat");
        add_voice(kPulpKitCymbalLevel, "Cymbal");
        add_voice(kPulpKitCowbellLevel, "Cowbell");
        add_voice(kPulpKitMaracasLevel, "Maracas");
    }

    void prepare(const format::PrepareContext& ctx) override {
        const double fs = ctx.sample_rate;
        kick_.prepare(fs);

        tom_low_.prepare(fs);
        tom_mid_.prepare(fs);
        tom_hi_.prepare(fs);
        apply_membrane_preset(tom_low_, MembranePreset::TomA);
        apply_membrane_preset(tom_mid_, MembranePreset::TomB);
        apply_membrane_preset(tom_hi_, MembranePreset::TomC);
        // The tom pads are calibrated to a per-pad decay knob (~0.90), not the
        // uniform 0.5 centre; capture each so the kit's Decay knob rides around
        // the calibrated tail instead of resetting it.
        tom_low_base_decay_ = membrane_calibration(MembranePreset::TomA).decay;
        tom_mid_base_decay_ = membrane_calibration(MembranePreset::TomB).decay;
        tom_hi_base_decay_ = membrane_calibration(MembranePreset::TomC).decay;

        snare_.prepare(fs);
        clap_.prepare(fs);
        clap_.set_config(clap_config());

        closed_hat_.prepare(fs);
        closed_hat_.set_config(closed_hat_config());
        open_hat_.prepare(fs);
        open_hat_.set_config(open_hat_config());
        cymbal_.prepare(fs);
        cymbal_.set_config(cymbal_config());

        cowbell_.prepare(fs);
        cowbell_.set_config(cowbell_config());

        rim_.prepare(fs);  // rim: ring at unity tune
        clave_.prepare(fs);
        clave_.set_tune(RimClaveVoice::kClaveTune);  // clave: bright woody ring

        maracas_.prepare(fs);
        maracas_.set_config(maracas_config());
    }

    void process(audio::BufferView<float>& output,
                 const audio::BufferView<const float>&,
                 midi::MidiBuffer& midi_in,
                 midi::MidiBuffer&,
                 const format::ProcessContext& ctx) override {
        // A timeline discontinuity clears every ring: the tails belong to a
        // moment the host has jumped away from. A trigger never resets a voice.
        if (ctx.should_reset_dsp_state()) reset_all();

        push_voice_controls();

        const double lv_kick = level_of(kPulpKitKickLevel);
        const double lv_snare = level_of(kPulpKitSnareLevel);
        const double lv_low = level_of(kPulpKitLowTomLevel);
        const double lv_mid = level_of(kPulpKitMidTomLevel);
        const double lv_hi = level_of(kPulpKitHiTomLevel);
        const double lv_rim = level_of(kPulpKitRimLevel);
        const double lv_clave = level_of(kPulpKitClaveLevel);
        const double lv_clap = level_of(kPulpKitClapLevel);
        const double lv_closed = level_of(kPulpKitClosedHatLevel);
        const double lv_open = level_of(kPulpKitOpenHatLevel);
        const double lv_cymbal = level_of(kPulpKitCymbalLevel);
        const double lv_cowbell = level_of(kPulpKitCowbellLevel);
        const double lv_maracas = level_of(kPulpKitMaracasLevel);

        auto left = output.channel(0);
        auto right = output.channel(output.num_channels() > 1 ? 1 : 0);
        const auto n_samples = static_cast<int32_t>(left.size());

        int32_t next_event = 0;
        const auto event_count = static_cast<int32_t>(midi_in.size());

        for (int32_t i = 0; i < n_samples; ++i) {
            // Dispatch every event timestamped at or before this sample so a
            // hit lands on the sample the host placed it on.
            while (next_event < event_count) {
                const auto& event = midi_in[static_cast<std::size_t>(next_event)];
                if (event.sample_offset > i) break;
                if (event.is_note_on() && event.velocity() > 0) {
                    dispatch(event.note(), event.velocity());
                }
                ++next_event;
            }

            // Every voice advances every sample; a silent voice contributes
            // zero. The sum is the kit mix. Per-voice level scales each voice's
            // own sample, so at the default 100% the mix is bit-identical to the
            // ungained sum.
            double s = kick_.process() * kVoltsToSample * kKickTrim * lv_kick;
            // Tom levels multiply each pad before the shared volt-domain scale,
            // so the three-pad sum keeps its exact grouping at unity gain.
            const double toms = tom_low_.process() * lv_low +
                                tom_mid_.process() * lv_mid +
                                tom_hi_.process() * lv_hi;
            s += toms * kVoltsToSample * kMembraneTrim;
            s += static_cast<double>(snare_.process()) * lv_snare;
            s += static_cast<double>(clap_.process()) * lv_clap;
            s += static_cast<double>(closed_hat_.process()) * lv_closed;
            s += static_cast<double>(open_hat_.process()) * lv_open;
            s += static_cast<double>(cymbal_.process()) * lv_cymbal;
            s += static_cast<double>(cowbell_.process()) * lv_cowbell;
            s += static_cast<double>(rim_.process()) * lv_rim;
            s += static_cast<double>(clave_.process()) * lv_clave;
            s += static_cast<double>(maracas_.process()) * lv_maracas;

            const auto sample = static_cast<float>(s);
            left[static_cast<std::size_t>(i)] = sample;
            if (output.num_channels() > 1) right[static_cast<std::size_t>(i)] = sample;
        }

        snap_denormals();
    }

private:
    /// Push every voice's four control knobs to its uniform setters. Called once
    /// per block, before the sample loop. Level is handled at the mix sum (a
    /// linear output gain), so only Tune/Decay/Tone go through the voice setters
    /// here; the snare additionally carries its Balance. Each setter recomputes
    /// coefficients in place and never allocates or locks, so this stays on the
    /// audio thread.
    void push_voice_controls() noexcept {
        // Kick: Tune and Decay pass through the reference calibration so the
        // stock knob positions land on the measured curve; Tone is the raw pot.
        kick_.set_tune(tune_of(kPulpKitKickTune) * kReferenceTuneTrim);
        kick_.set_decay(reference_decay_taper(decay01_of(kPulpKitKickDecay)));
        kick_.set_tone(tone01_of(kPulpKitKickTone));

        snare_.set_tune(static_cast<float>(tune_of(kPulpKitSnareTune)));
        snare_.set_decay(static_cast<float>(decay01_of(kPulpKitSnareDecay)));
        snare_.set_tone(static_cast<float>(tone01_of(kPulpKitSnareTone)));
        // Base-centre the balance like the toms' decay: the snare's calibrated
        // default is noise-dominated (kDefaultBalance = 0.70), not 0.50, so the
        // knob rides around it -- 50% keeps the calibrated sound, and the ends
        // sweep tone-only to snap-only.
        snare_.set_balance(std::clamp(
            SnareVoice::kDefaultBalance + (pct_of(kPulpKitSnareBalance) - 0.5), 0.0, 1.0));

        push_membrane(tom_low_, kPulpKitLowTomLevel, tom_low_base_decay_);
        push_membrane(tom_mid_, kPulpKitMidTomLevel, tom_mid_base_decay_);
        push_membrane(tom_hi_, kPulpKitHiTomLevel, tom_hi_base_decay_);

        rim_.set_tune(static_cast<float>(tune_of(kPulpKitRimTune)));
        rim_.set_decay(static_cast<float>(decay01_of(kPulpKitRimDecay)));
        rim_.set_tone(static_cast<float>(tone01_of(kPulpKitRimTone)));

        // The clave is the same voice as the rim, lifted to a woodier ring by a
        // fixed tune ratio; the kit's Clave Tune knob rides around that ratio so
        // the default (1.0) keeps the calibrated clave pitch.
        clave_.set_tune(
            static_cast<float>(tune_of(kPulpKitClaveTune) * RimClaveVoice::kClaveTune));
        clave_.set_decay(static_cast<float>(decay01_of(kPulpKitClaveDecay)));
        clave_.set_tone(static_cast<float>(tone01_of(kPulpKitClaveTone)));

        clap_.set_tune(static_cast<float>(tune_of(kPulpKitClapTune)));
        clap_.set_decay(static_cast<float>(decay01_of(kPulpKitClapDecay)));
        clap_.set_tone(static_cast<float>(tone01_of(kPulpKitClapTone)));

        push_metallic(closed_hat_, kPulpKitClosedHatLevel);
        push_metallic(open_hat_, kPulpKitOpenHatLevel);
        push_metallic(cymbal_, kPulpKitCymbalLevel);

        cowbell_.set_tune(static_cast<float>(tune_of(kPulpKitCowbellTune)));
        cowbell_.set_decay(static_cast<float>(decay01_of(kPulpKitCowbellDecay)));
        cowbell_.set_tone(static_cast<float>(tone01_of(kPulpKitCowbellTone)));

        maracas_.set_tune(static_cast<float>(tune_of(kPulpKitMaracasTune)));
        maracas_.set_decay(static_cast<float>(decay01_of(kPulpKitMaracasDecay)));
        maracas_.set_tone(static_cast<float>(tone01_of(kPulpKitMaracasTone)));
    }

    /// A tom (membrane) voice takes Tune and Tone as raw knobs, but its Decay
    /// rides around the per-pad calibrated centre @p base_decay: the kit knob's
    /// 50% reproduces the pad's tail, and turning it lengthens or shortens the
    /// ring around it. @p level_base is the voice's first (Level) param id, used
    /// only to reach the sibling Tune/Decay/Tone by offset.
    void push_membrane(MembraneVoice& v, state::ParamID level_base,
                       double base_decay) noexcept {
        v.set_tune(static_cast<float>(tune_of(level_base + 1)));
        const double knob = decay01_of(level_base + 2);
        v.set_decay(static_cast<float>(std::clamp(base_decay + (knob - 0.5), 0.0, 1.0)));
        v.set_tone(static_cast<float>(tone01_of(level_base + 3)));
    }

    /// A metallic voice (hats, cymbal) self-centres its uniform setters on its
    /// installed preset, so the raw knobs pass straight through. @p level_base is
    /// the Level param id; Tune/Decay/Tone are the next three ids.
    void push_metallic(MetallicVoice& v, state::ParamID level_base) noexcept {
        v.set_tune(static_cast<float>(tune_of(level_base + 1)));
        v.set_decay(static_cast<float>(decay01_of(level_base + 2)));
        v.set_tone(static_cast<float>(tone01_of(level_base + 3)));
    }

    /// Route a note-on to its voice. Velocity is delivered as accent volts to
    /// the strike-excited membrane voices (kick, toms) and as a normalized
    /// [0,1] level to the envelope-gated voices. A closed hat chokes the open
    /// hat, the one cross-voice interaction in the kit.
    void dispatch(uint8_t note, uint8_t velocity) noexcept {
        const double v01 = static_cast<double>(velocity) / 127.0;
        const double accent = accent_volts(velocity);
        switch (note) {
            case 36: kick_.trigger(accent); break;
            case 37: rim_.trigger(v01); break;
            case 38:
            case 40: snare_.trigger(v01); break;
            case 39: clap_.trigger(static_cast<float>(v01)); break;
            case 41:
            case 43: tom_low_.trigger(accent); break;
            case 45:
            case 47: tom_mid_.trigger(accent); break;
            case 48:
            case 50: tom_hi_.trigger(accent); break;
            case 42:
            case 44:
                closed_hat_.trigger(static_cast<float>(v01));
                open_hat_.choke();
                break;
            case 46: open_hat_.trigger(static_cast<float>(v01)); break;
            case 49: cymbal_.trigger(static_cast<float>(v01)); break;
            case 51:
            case 56: cowbell_.trigger(static_cast<float>(v01)); break;
            case 70: maracas_.trigger(static_cast<float>(v01)); break;
            case 75: clave_.trigger(v01); break;
            default: break;  // note outside the kit map -- ignore
        }
    }

    void reset_all() noexcept {
        kick_.reset();
        tom_low_.reset();
        tom_mid_.reset();
        tom_hi_.reset();
        snare_.reset();
        clap_.reset();
        closed_hat_.reset();
        open_hat_.reset();
        cymbal_.reset();
        cowbell_.reset();
        rim_.reset();
        clave_.reset();
        maracas_.reset();
    }

    void snap_denormals() noexcept {
        kick_.snap_denormals();
        tom_low_.snap_denormals();
        tom_mid_.snap_denormals();
        tom_hi_.snap_denormals();
        rim_.snap_denormals();
        clave_.snap_denormals();
    }

    /// A voice's Level knob (percent) as a linear output multiplier.
    double level_of(state::ParamID id) const noexcept {
        return state().get_value(id) / 100.0;
    }
    /// A Tune knob as a raw pitch ratio (already in ratio units).
    double tune_of(state::ParamID id) const noexcept {
        return static_cast<double>(state().get_value(id));
    }
    /// A Decay/Tone knob (percent) as a normalized 0..1 value.
    double decay01_of(state::ParamID id) const noexcept {
        return state().get_value(id) / 100.0;
    }
    double tone01_of(state::ParamID id) const noexcept {
        return state().get_value(id) / 100.0;
    }
    /// A percent knob as a normalized 0..1 fraction.
    double pct_of(state::ParamID id) const noexcept {
        return state().get_value(id) / 100.0;
    }

    /// Velocity as trigger-pulse amplitude in volts (4..14 V over the accent
    /// range), the excitation the strike-driven bridged-T voices consume.
    static double accent_volts(uint8_t velocity) noexcept {
        constexpr double min_v = 4.0;
        constexpr double max_v = 14.0;
        return min_v + (max_v - min_v) * (static_cast<double>(velocity) / 127.0);
    }

    /// Volts to full-scale for the supply-rail-referenced circuit voices.
    static constexpr double kVoltsToSample = 1.0 / 15.0;
    /// Loudness match of the volt-domain voices to the reference renders.
    static constexpr double kKickTrim = 0.667;
    static constexpr double kMembraneTrim = 0.667;

    BassDrumVoice kick_{};
    MembraneVoice tom_low_{};
    MembraneVoice tom_mid_{};
    MembraneVoice tom_hi_{};
    SnareVoice snare_{};
    ClapVoice clap_{};
    MetallicVoice closed_hat_{};
    MetallicVoice open_hat_{};
    MetallicVoice cymbal_{};
    CowbellVoice cowbell_{};
    RimClaveVoice rim_{};
    RimClaveVoice clave_{};
    MaracasVoice maracas_{};

    // Per-pad calibrated tom decay centres, captured at prepare().
    double tom_low_base_decay_ = 0.5;
    double tom_mid_base_decay_ = 0.5;
    double tom_hi_base_decay_ = 0.5;
};

inline std::unique_ptr<format::Processor> create_pulp_kit() {
    return std::make_unique<PulpKit>();
}

}  // namespace pulp::examples
