#pragma once

// The kit's snare voice: two struck drum bodies plus a filtered-noise "snappy",
// balanced against each other. This is the whole 808-style snare architecture.
//
//   * The two bodies are the drum shell's tone. Each is a StruckBridgedT ringing
//     at a fixed pitch (~168 Hz and ~330 Hz) -- the same bridged-T network the
//     bass drum is built from, tuned up and rung short. Two of them, an octave
//     or so apart, give the shell its slightly detuned, hollow "donk".
//   * The snappy is the snare wires rattling against the underside of the head:
//     a burst of white noise through a fast decay envelope and a broad bandpass,
//     bright and short. It carries most of the sound's energy and all of its
//     "sss".
//   * A tone/snap balance sets how much of each you hear, from a pure shell tone
//     to a pure noise crack. It is the snare's most characterful control.
//
// Why the tail is tonal while the onset is bright: the noise burst decays in
// ~90 ms but the bodies ring for ~250 ms, so the strike is a broadband crack
// that settles into the shell's low ring. That split is audible and it is what
// separates a snare from a hi-hat -- a hat is the crack with no body under it.
//
// Calibration: the body pitches, the two feedback gains (which set the bodies'
// decay), the snappy's bandpass and envelope, and the default balance are fit
// to the reference snare pad's measured onset centroid (~6.7 kHz), spectral
// flatness (~0.6), decay (~0.24 s) and peak. Every sample is still generated by
// the circuit -- the bodies by the bridged-T recursion, the snappy by a live
// noise source through real filters. Nothing is sampled or looked up.
//
// RT contract: prepare() sizes and clears state; trigger() and process()
// allocate nothing and never lock. A trigger superposes onto the live body
// rings (they are never reset on a hit) while re-arming the noise gate, so
// repeated hits interfere in the shell and get freshly decorrelated snare
// noise -- no machine-gun on either component.

#include "struck_bridged_t.hpp"

#include <pulp/signal/denormal.hpp>
#include <pulp/signal/svf.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>

namespace pulp::examples {

namespace snare_detail {

/// A deterministic white-noise source (xorshift32) mapped to [-1, 1). Seeded
/// once at prepare and free-running thereafter, so successive triggers draw
/// decorrelated noise rather than replaying an identical burst.
struct WhiteNoise {
    std::uint32_t state = 0x12345678u;
    void reset() noexcept { state = 0x12345678u; }
    float next() noexcept {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        return static_cast<float>(static_cast<std::int32_t>(state)) * (1.0f / 2147483648.0f);
    }
};

}  // namespace snare_detail

class SnareVoice {
public:
    // Reference-calibrated defaults. The body pitches and feedback gains place
    // the shell's two rings on the measured pad; the snappy filter and default
    // envelope place its onset brightness and decay on the measured pad.
    static constexpr double kBody1Hz = 168.0;
    static constexpr double kBody2Hz = 330.0;
    static constexpr double kBody1Feedback = 0.855;  ///< ~0.24 s ring at kBody1Hz.
    static constexpr double kBody2Feedback = 0.885;  ///< ~0.24 s ring at kBody2Hz.
    static constexpr double kBody2StrikeScale = 0.8;  ///< upper body struck a touch softer.
    static constexpr double kSnappyHighpassHz = 800.0;
    static constexpr double kSnappyBandpassHz = 4200.0;
    static constexpr double kSnappyBandpassQ = 0.65;
    static constexpr double kDefaultBalance = 0.70;  ///< noise-dominated, per the reference.
    /// Master gain that lands a full-velocity hit at the reference pad's peak.
    static constexpr double kOutputGain = 1.40;

    void prepare(double sample_rate) noexcept {
        sample_rate_ = sample_rate;
        body1_.prepare(sample_rate);
        body1_.set_frequency(kBody1Hz * tune_);
        body1_.set_feedback(kBody1Feedback);
        body2_.prepare(sample_rate);
        body2_.set_frequency(kBody2Hz * tune_);
        body2_.set_feedback(kBody2Feedback);

        highpass_.set_sample_rate(static_cast<float>(sample_rate));
        highpass_.set_mode(signal::Svf::Mode::highpass);
        highpass_.set_frequency(static_cast<float>(kSnappyHighpassHz));
        highpass_.set_resonance(0.7f);
        bandpass_.set_sample_rate(static_cast<float>(sample_rate));
        bandpass_.set_mode(signal::Svf::Mode::bandpass);
        bandpass_.set_resonance(static_cast<float>(kSnappyBandpassQ));
        update_snappy_tone();  // sets bandpass centre from tone_knob_ (0.5 -> 4200 Hz)

        update_snappy_decay();
        reset();
    }

    void reset() noexcept {
        body1_.reset();
        body2_.reset();
        highpass_.reset();
        bandpass_.reset();
        noise_.reset();
        snappy_env_ = 0.0;
    }

    /// Strike the snare. @p velocity in [0, 1] scales both the body strike and
    /// the snappy burst, so peak level tracks velocity linearly -- velocity is
    /// loudness here, as on the reference pad, not a timbre change.
    void trigger(double velocity) noexcept {
        velocity = std::clamp(velocity, 0.0, 1.0);
        body1_.strike(velocity);
        body2_.strike(velocity * kBody2StrikeScale);
        snappy_env_ = velocity;  // re-arm the noise gate for this hit
    }

    /// Advance one sample.
    float process() noexcept {
        const double tone = 0.5 * (body1_.process() + body2_.process());
        const double noise = bandpass_.process(highpass_.process(noise_.next()));
        const double snappy = noise * snappy_env_;
        snappy_env_ = signal::snap_to_zero(snappy_env_ * snappy_decay_coeff_);
        const double mix = (1.0 - balance_) * tone + balance_ * snappy;
        return static_cast<float>(signal::snap_to_zero(level_ * kOutputGain * mix));
    }

    // --- Uniform kit-voice control surface --------------------------------
    // Four setters shared by every kit voice, identical signatures. Their
    // calibrated centres reproduce today's snare bit-for-bit:
    //   set_level(1) / set_tune(1) / set_decay(0.5) / set_tone(0.5).
    // The controls only add range around that point.

    /// Output gain in [0, 1]; 1.0 is the reference-calibrated loudness (a full
    /// hit at the pad's peak). Linear, so set_level(0.5) halves the peak.
    void set_level(float level01) noexcept {
        level_ = std::clamp(static_cast<double>(level01), 0.0, 1.0);
    }
    double level() const noexcept { return level_; }

    /// Snappy brightness in [0, 1]: an exponential tilt of the noise bandpass
    /// centre around its calibrated 4200 Hz, one octave down at 0 to one octave
    /// up at 1. 0.5 is the reference centre, so it raises/lowers the onset
    /// spectral centroid without moving the default.
    void set_tone(float tone01) noexcept {
        const double t = std::clamp(static_cast<double>(tone01), 0.0, 1.0);
        if (t == tone_knob_) return;
        tone_knob_ = t;
        update_snappy_tone();
    }
    double tone() const noexcept { return tone_knob_; }

    /// Tone/snap balance in [0, 1]: 0 is the bare shell tone, 1 is the bare
    /// noise crack. Default is noise-dominated to match the reference.
    void set_balance(double balance) noexcept {
        balance_ = std::clamp(balance, 0.0, 1.0);
    }
    double balance() const noexcept { return balance_; }

    /// Snappy decay knob in [0, 1], mapped to a noise-gate T60 of ~40..220 ms.
    /// Only the snare wires' rattle length moves; the shell ring is fixed by the
    /// bodies. The default (0.5) is the reference's ~90 ms snappy.
    void set_decay(float decay01) noexcept {
        const double knob01 = std::clamp(static_cast<double>(decay01), 0.0, 1.0);
        if (knob01 == decay_knob_) return;
        decay_knob_ = knob01;
        update_snappy_decay();
    }
    double decay() const noexcept { return decay_knob_; }

    /// Retune both bodies by a common ratio; 1.0 is the calibrated pitch. The
    /// snappy is unaffected -- tuning a snare moves the shell pitch, not the
    /// wire noise.
    void set_tune(float ratio) noexcept {
        const double r = std::clamp(static_cast<double>(ratio), 0.25, 4.0);
        if (r == tune_) return;
        tune_ = r;
        body1_.set_frequency(kBody1Hz * tune_);
        body2_.set_frequency(kBody2Hz * tune_);
    }
    double tune() const noexcept { return tune_; }

    void snap_denormals() noexcept {
        body1_.snap_denormals();
        body2_.snap_denormals();
        snappy_env_ = signal::snap_to_zero(snappy_env_);
    }

private:
    void update_snappy_decay() noexcept {
        // Exponential knob: T60 = 40 ms .. 220 ms, with the 0.5 default at ~94 ms.
        const double t60 = 0.04 * std::pow(0.22 / 0.04, decay_knob_);
        const double tau = t60 / 6.9077552789821;  // T60 = tau * ln(1000)
        snappy_decay_coeff_ = std::exp(-1.0 / (tau * sample_rate_));
    }

    void update_snappy_tone() noexcept {
        // Exponential tilt of the snappy bandpass centre around its calibrated
        // 4200 Hz: one octave down at tone=0, one octave up at tone=1, exactly
        // 4200 Hz at the 0.5 default (pow(2, 0) == 1). This raises/lowers the
        // onset spectral centroid without touching the default sound.
        const double centre = kSnappyBandpassHz * std::pow(2.0, (tone_knob_ - 0.5) * 2.0);
        bandpass_.set_frequency(static_cast<float>(centre));
    }

    StruckBridgedT body1_{};
    StruckBridgedT body2_{};
    signal::Svf highpass_{};
    signal::Svf bandpass_{};
    snare_detail::WhiteNoise noise_{};

    double sample_rate_ = 48000.0;
    double balance_ = kDefaultBalance;
    double decay_knob_ = 0.5;
    double tune_ = 1.0;
    double tone_knob_ = 0.5;  ///< 0.5 == calibrated 4200 Hz snappy bandpass centre.
    double level_ = 1.0;      ///< 1.0 == calibrated loudness; linear output gain.
    double snappy_env_ = 0.0;
    double snappy_decay_coeff_ = 0.0;
};

}  // namespace pulp::examples
